# Wejście na dockera z PHP docker exec -i -t php /bin/bash
# Wersja 2 pozwala na przekazywanie argumentów
# Aliasy https://docs.docker.com/compose/compose-file/#aliases

version: '3'

services:
#  vcb-redis:
#    image: 'bitnami/redis:latest'
#    container_name: vcb_redis.local
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    labels:
#      kompose.service.type: nodeport
#    ports:
#      - 6379:6379
#    volumes:
#      - redis_data:/bitnami/redis
#    networks:
#      - esnet

  shop_list-db:
    container_name: shop_list_postgres.local
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    volumes:
      - ./sql/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    networks:
      - esnet

  shop_list-web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DATABASE_HOST=shop_list_postgres.local
    links:
      - shop_list-db
#      - vcb-redis
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
#  redis_data:
#    driver: local

networks:
  esnet:
